# Static web site compiler
FROM node:14 as builder

# GENERIC BUILG ARGS
ARG COMMIT_SHA
ENV COMMIT_SHA=${COMMIT_SHA}
ARG VOCDONI_ENVIRONMENT="dev"
ENV VOCDONI_ENVIRONMENT=${VOCDONI_ENVIRONMENT}
ARG NODE_ENV="development"
ENV NODE_ENV=${NODE_ENV}
ARG DEFAULT_ETH_CHAIN_ID
ENV DEFAULT_ETH_CHAIN_ID=${DEFAULT_ETH_CHAIN_ID}
ARG SIGNALING_ORACLE_URL="https://signaling-oracle.dev.vocdoni.net/dvote"
ENV SIGNALING_ORACLE_URL=${SIGNALING_ORACLE_URL}
ARG ANALYTICS_KEY="1w2W1aAJRMbVRAgHVOIRVVIh1Nc"
ENV ANALYTICS_KEY=${ANALYTICS_KEY}
ARG FORTMATIC_API_KEY="pk_test_A5D318B08D001541"
ENV FORTMATIC_API_KEY=${FORTMATIC_API_KEY}
ARG WALLET_CONNECT_ID="b76cba91dc954ceebff27244923224b1"
ENV WALLET_CONNECT_ID=${WALLET_CONNECT_ID}
ARG DEFAULT_ETH_CHAIN_ID="1"
ENV DEFAULT_ETH_CHAIN_ID=${DEFAULT_ETH_CHAIN_ID}

# NETWORK DEPENDENT BUILD ARGS
ARG MAINNET_VOCDONI_ENVIRONMENT="prod"
ENV MAINNET_VOCDONI_ENVIRONMENT=${MAINNET_VOCDONI_ENVIRONMENT}
ARG MATIC_VOCDONI_ENVIRONMENT="stg"
ENV MATIC_VOCDONI_ENVIRONMENT=${MATIC_VOCDONI_ENVIRONMENT}
ARG RINKEBY_VOCDONI_ENVIRONMENT="stg"
ENV RINKEBY_VOCDONI_ENVIRONMENT=${RINKEBY_VOCDONI_ENVIRONMENT}

ARG MAINNET_BOOTNODE_URL="https://bootnodes.vocdoni.net/gateways.json"
ENV MAINNET_BOOTNODE_URL=${MAINNET_BOOTNODE_URL}
ARG MATIC_BOOTNODE_URL="https://bootnodes.vocdoni.net/gateways.stg.json"
ENV MATIC_BOOTNODE_URL=${MATIC_BOOTNODE_URL}
ARG RINKEBY_BOOTNODE_URL="https://bootnodes.vocdoni.net/gateways.stg.json"
ENV RINKEBY_BOOTNODE_URL=${RINKEBY_BOOTNODE_URL}

ARG MAINNET_SIGNALING_ORACLE_URL="https://signaling-oracle.vocdoni.net/dvote"
ENV MAINNET_SIGNALING_ORACLE_URL=${MAINNET_SIGNALING_ORACLE_URL}
ARG MATIC_SIGNALING_ORACLE_URL="https://signaling-oracle.dev.vocdoni.net/dvote"
ENV MATIC_SIGNALING_ORACLE_URL=${MATIC_SIGNALING_ORACLE_URL}
ARG RINKEBY_SIGNALING_ORACLE_URL="https://signaling-oracle.dev.vocdoni.net/dvote"
ENV RINKEBY_SIGNALING_ORACLE_URL=${RINKEBY_SIGNALING_ORACLE_URL}

ARG MAINNET_ARCHIVE_IPNS_ID="k2k4r8prjy8gxj5ozkfvc1n9ih5ssn7yjcu8k3u2v5g2711j8rohu0ks"
ENV MAINNET_ARCHIVE_IPNS_ID=${MAINNET_ARCHIVE_IPNS_ID}
ARG MATIC_ARCHIVE_IPNS_ID=""
ENV MATIC_ARCHIVE_IPNS_ID=${MATIC_ARCHIVE_IPNS_ID}
ARG RINKEBY_ARCHIVE_IPNS_ID=""
ENV RINKEBY_ARCHIVE_IPNS_ID=${RINKEBY_ARCHIVE_IPNS_ID}

WORKDIR /app
ADD package.json /app
# ADD package-lock.json /app
RUN npm install -f

ADD . /app
RUN npm run export

FROM node:14

RUN apt update && apt install nginx -y && apt clean

COPY --from=builder /app /app

WORKDIR /app

ENTRYPOINT [ "/app/entrypoint.sh" ]
