# Static web site compiler
FROM node:14 as builder

ARG NODE_ENV="development"
ARG VOCDONI_ENVIRONMENT="prod"
ARG ETH_NETWORK_ID="mainnet"
ARG ETH_CHAIN_ID=1
ARG BLOCK_TIME=10
ARG BOOTNODES_URL="https://bootnodes.vocdoni.net/gateways.json"

ADD . /app
WORKDIR /app
RUN npm install && npm run export

## Static web server
FROM nginx:1.19

COPY --from=builder /app/build /usr/share/nginx/html
