export const INVALID_CHAIN_ID = "Invalid chain ID"
export const METAMASK_IS_NOT_AVAILABLE = "Metamask is not available"
export const YOU_ARE_NOT_CONNECTED = "You are not connected"
export const NO_TOKEN_BALANCE = "You have no token balance"
export const TOKEN_ALREADY_REGISTERED = "The token is already registered"
